

<?php include 'header.phtml'?>

<form action="añadirDestinos" method ="POST" class="my-4";>
    <div class="row">

        <h3>Agregar Destinos</h3>

        <div class="col3">
            <div class="form-group">
                <label>Pais</label>
                <input name="pais"type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Ciudad</label>
                <input name="ciudad"type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Actividades</label>
                <input name="actividades"type="text" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label>PRECIO</label>
            <input name="precio"type="number" class="form-control">
        </div>
    </div>
</div>
<button type="submit" class="btn btn-primary">Guardar</button>

</form>