<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>TP OBLIGARORIO</title>
</head>
<body>
<header>
    <div class="navbar">
        <div>
        <a class="navbar-brand" href ="listar">Destinos</a>
        </div>
        <div>
        <a class="navbar-brand" href="añadir">añadir</a>
        </div>
        <a class="navbar-brand" href="">Nosotros</a>
        <div>
        <a class="navbar-brand" href="showLogin">Login</a>
        </div>
        <?php if ($this->user): ?>
        <div>
        <a class="navbar-brand" href="Logout">Logout</a>
        </div>
        <?php endif;?>
        <span class="navbar-toggler-icon"></span>
    </div>
</header>
    
</body>
</html>