<?php 
include 'header.phtml';

echo "<h2>Destinos:</h2>";
echo "<ul class='destinos-db'>";
foreach($destinos as $destino){ ?>

        <div class ='listado_destinos'>
        <li class = "lista_items"><b><?php echo 'Pais' ?></b> | (<?php echo $destino -> pais ?>) </b></li>  
        <li class = "lista_items"><b><?php echo 'Ciudad' ?></b> | (<?php echo $destino -> ciudad ?>) </b></li>
        <li class = "lista_items"><b><?php echo 'Actividad' ?></b> | (<?php echo $destino -> actividades ?>) </b></li>
        <li class = "lista_items"><b><?php echo 'Precio' ?></b> | (<?php echo $destino -> precio ?>) </b> </li>               
        <a href= "borrar/<?php echo $destino->id_destinos ?>" type = "button" class = 'btn btn-danger ml-auto borrar-destinos'>Borrar</a>
        <a href= "mostrar/<?php echo $destino->id_destinos ?>" class = 'btn btn-primary'>visualizar</a>
        </div>


<?php }
echo "</ul>";
?>
